name: build static binaries
on: [workflow_dispatch]
jobs:
   build-linux:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
           go-version: 1.18
      - name: build linux static binary
        run: go build main.go
      - name: upload linux static binary
        uses: actions/upload-artifact@v3.1.0
        with:
           name: bindless-linux-64bits
           path: main
